FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    zip \
    unzip \
    git \
    libzip-dev \
    bash \
    && docker-php-ext-install zip pdo pdo_mysql \
    && pecl install redis \
    && docker-php-ext-enable redis

COPY .deploy/php.ini /usr/local/etc/php/

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY .deploy/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

WORKDIR /var/www/html
COPY . .

CMD ["php-fpm"]

USER $user
